services:
  mysql:
    image: 'mysql:8.0'
    container_name: 'mysql_db'
    environment:
      - 'MYSQL_DATABASE=gestaoProcessoEtico'
      - 'MYSQL_ROOT_PASSWORD=password'
    ports:
      - '3307:3306'